# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/api.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'api/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rapi/api.proto\x12\x03\x61pi\"2\n\x08\x45nvelope\x12\x1b\n\x05hello\x18\x01 \x01(\x0b\x32\n.api.HelloH\x00\x42\t\n\x07message\"\x18\n\x05Hello\x12\x0f\n\x07message\x18\x01 \x01(\t\"5\n\x07Indices\x12\r\n\x05index\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\"3\n\x06Stocks\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\"\x8a\x01\n\x05Ohlcv\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04open\x18\x02 \x01(\x02\x12\x0c\n\x04high\x18\x03 \x01(\x02\x12\x0b\n\x03low\x18\x04 \x01(\x02\x12\r\n\x05\x63lose\x18\x05 \x01(\x02\x12\x0e\n\x06volume\x18\x06 \x01(\x03\x12\x14\n\x0ctotal_trades\x18\x07 \x01(\x03\x12\x15\n\rqty_per_trade\x18\x08 \x01(\x02\"1\n\x10ListIndicesReply\x12\x1d\n\x07indices\x18\x01 \x03(\x0b\x32\x0c.api.Indices\"*\n\x18ListIndicesStocksRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"5\n\x16ListIndicesStocksReply\x12\x1b\n\x06stocks\x18\x01 \x03(\x0b\x32\x0b.api.Stocks\"H\n\x10StockDataRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\"+\n\x0eStockDataReply\x12\x19\n\x05ohlcv\x18\x01 \x03(\x0b\x32\n.api.Ohlcvb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE']._serialized_start=22
  _globals['_ENVELOPE']._serialized_end=72
  _globals['_HELLO']._serialized_start=74
  _globals['_HELLO']._serialized_end=98
  _globals['_INDICES']._serialized_start=100
  _globals['_INDICES']._serialized_end=153
  _globals['_STOCKS']._serialized_start=155
  _globals['_STOCKS']._serialized_end=206
  _globals['_OHLCV']._serialized_start=209
  _globals['_OHLCV']._serialized_end=347
  _globals['_LISTINDICESREPLY']._serialized_start=349
  _globals['_LISTINDICESREPLY']._serialized_end=398
  _globals['_LISTINDICESSTOCKSREQUEST']._serialized_start=400
  _globals['_LISTINDICESSTOCKSREQUEST']._serialized_end=442
  _globals['_LISTINDICESSTOCKSREPLY']._serialized_start=444
  _globals['_LISTINDICESSTOCKSREPLY']._serialized_end=497
  _globals['_STOCKDATAREQUEST']._serialized_start=499
  _globals['_STOCKDATAREQUEST']._serialized_end=571
  _globals['_STOCKDATAREPLY']._serialized_start=573
  _globals['_STOCKDATAREPLY']._serialized_end=616
# @@protoc_insertion_point(module_scope)
