# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api import api_pb2 as api_dot_api__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NumberSortingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SortNumbers = channel.unary_unary(
                '/api.NumberSortingService/SortNumbers',
                request_serializer=api_dot_api__pb2.NumberArray.SerializeToString,
                response_deserializer=api_dot_api__pb2.NumberArray.FromString,
                _registered_method=True)


class NumberSortingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SortNumbers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NumberSortingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SortNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.SortNumbers,
                    request_deserializer=api_dot_api__pb2.NumberArray.FromString,
                    response_serializer=api_dot_api__pb2.NumberArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.NumberSortingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.NumberSortingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NumberSortingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SortNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.NumberSortingService/SortNumbers',
            api_dot_api__pb2.NumberArray.SerializeToString,
            api_dot_api__pb2.NumberArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
