name: stock_wave
description: "Stock Wave"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  k_chart: ^0.7.1
  cupertino_icons: ^1.0.8
  grpc: ^4.0.1
  protobuf: ^3.1.0
  path_provider: ^2.1.4
  path: ^1.9.0
  injectable:
  get_it:
  auto_route: ^9.2.2
  fluent_ui: ^4.9.1
  macos_window_utils: ^1.5.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_riverpod: ^2.4.0
  flex_seed_scheme: ^3.4.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner: ^2.4.6
  auto_route_generator: ^9.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/server_py_flutter_osx